data/2018-09-25/raw/invasive_species.R

The old regular expression only selected the first word of the species or country name, resulting in incomplete names such as "Sri" for "Sri Lanka". 
The new regular expression selects everything after the first letter. Any numbers at the start are discarded, but the full country or species name is retained.

Fix regular expressions for countries and species

---

data/2020/2020-02-25/readme.md

suggest change to "academic year"
Note that the data at `year` do not appear to be districts
```r
> df_measles %>% pull(year) %>% unique
[1] "2018-19" "2017-18" "null"    "2017"   
```

Description for `year` variable seems to be wrong

---

data/2020/2020-06-09/science.csv

URL for Harold Amos was duplicated (rows 1 & 2) and URL for Roger Arliner Young was missing (row 120).
```
links <- science$links %>% 
tail(-1) %>% 
c(., "https://en.wikipedia.org/wiki/Roger_Arliner_Young")
science <- science %>% 
select(-links) %>% 
mutate(links = links)
readr::write_csv(science, "science.csv")
```

correct Wikipedia URLs in science.csv

---

data/2020/2020-06-16/readme.md

On the slave_routes, and african_names data sets, there were two "<-" I removed the extra one so others can just copy/paste.

Remove double "<-" from Get the data

---

data/2020/2020-10-27/readme.md

replacing hyphen with underscore to avoid object not found error when reading int he data manually or with the `tidytuesdayR `package.

replacing hyphen with underscore

---

data/2021/2021-01-12/readme.md

Updated blog posts to current urls and one twitter account that is no longer active changed to their website.

fix dead links for Jan 12 - Art Collections

---

README.md

I added a plain text and bibtex citation suggestion as well as a note about citing the tidytuesdayR package separately.
GitHub's official suggestion for citing repositories requires that repo releases get a DOI. See https://guides.github.com/activities/citable-code/ for more. If you wanted to that route the citation could be updated accordingly. I imagine that an annual release would suffice if you wanted to go that route.

Add citation suggestion

---

data/2021/2021-02-09/readme.md

It was lifetime_earnings.csv [which is 404] when it should direct to lifetime_earn.csv

First dataset is incorrectly named in read_csv

---

data/2021/2021-04-27/readme.md

Spelling correction abov -> above, although it's actually "below"

Spelling in readme.md

---

static/tt_data_type.csv

Error in file name referred to in tt_data_type.csv as mentioned in #353 Corrected this to match the file in the data directory for 2021-07-06.

Fixed 2021-07-06 data_files in tt_data_type.csv

---

data/2022/2022-05-31/axios.csv
data/2022/2022-05-31/readme.md
data/2022/2022-05-31/reputation.csv

There seems to be some discrepancy between the Axios/Harris numbers and the ones in this repo. The Trump Org numbers in [data/2022/2022-05-31/reputation.csv](https://github.com/rfordatascience/tidytuesday/pull/442/files/3643580c6b4621eb56f6ec622ca43242d7f51a4a#diff-db694ac0875faa3940ddb2bb63042141327e09360591ef238533757389fb87f4) seem to be a particularly stark difference. 
I've rerun the script in README using a JS link I found in the HTML source.

2022 W22 changed data source?

---

README.md

I just deleted an space in yesterday's dataset article link, it was producing the markdown rendering to fail

Delete wrong space

---

data/2021/2021-08-24/readme.md

taxon code for the fat-tailed dwarf lemur is listed incorrectly as "CMEAD", it is actually "CMED" in the dataset

Correct typo CMEAD -> CMED

---

data/2022/2022-12-13/README.md

Existing URLs in guidance on ANSI codes return 404 error. Looks like a hyphen in URL was omitted (codelists, instead of code-lists). Adding it back in to returns 200 (https://www.census.gov/library/reference/code-lists/ansi/ansi-codes-for-states.html).

Fix two broken URLs to US Census Bureau website

---

data/2022/2022-11-29/wcmatches.csv

Changed the winning_team value in row 35 from "West Germany" to "Germany". I think this was a typo as the away_team value is set to "Germany" and West Germany was not a country in 1934.

Updated wcmatches.csv

---

data/2022/2022-11-29/wcmatches.csv

In row 263 of wcmatches.csv, home_team value is "East Germany" so I changed losing_team value from "West Germany" to "East Germany". I also made sure to verify that East Germany was playing in this match rather than West Germany.

Updated typo in wcmatches.csv

---

data/2021/2021-08-24/taxonomy.csv

The README and raw data reference CMED, but the mapping file contains CMEAD.

fix: Error in Lemur taxonomy mapping file

---

data/2024/2024-02-13/readme.md

The week 7 Valentine's Day comsumer data instructions for reading in the data with the tidytuesdayR package don't need file extensions.

Remove .csv extension from week 7 data instructions

---

data/2024/2024-03-12/readme.md

I think the regex seperator for the `eligibility_criteria`, `project_types`, `services`, and `fiscal_sponsorship_model` columns is supposed to be `\\|` not `\\n`

[2024-03-12] Use correct separator

---

.github/workflows/pr-assign-command.yaml

They MIGHT not have the latest DESCRIPTION file, but this action will still run, so make sure usethis gets installed.

Proactively grab usethis

---

.github/pr_instructions.md
data/curated/template/instructions.md
data/curated/template/meta.yaml
data/curated/template/saving.R

I made some edits to the PR instructions.
Edits I didn't make but think we should clarify: What is meant by directory name in the `saving.R` file? Is that the same as the folder they created in their branch? Is the `{dataset}.md` file generated after running `saving.R`?

Lg update pr instructions

---

static/templates/metadata.R

Drop trailing spaces during metadata processing.

Get rid of trailing spaces in yaml lines.

---

static/templates/how_to_participate.md
static/templates/the_data.md

Hello, Jon! I've added the python info to the templates in the same way I added it to this week's FBI data readme. I know your script behind the scenes builds each week's readme using params for year and date and so on, and I'm hoping that it will build the python chunk in the same way as the R chunk. The last thing I want to do is make more work for you! 
Libby
Thank you for your submission! Please leave this text as-is when you submit, and then check the checklist.
Usability:
Preparation:

Adding python + posit references to templates

---

.github/workflows/pr-assign-command.yaml
data/curated/template/intro.md
static/templates/assign_week.R
static/templates/readme.R
tidytuesday.Rproj

Lay out intro.md to try to make it harder for submitters to get confused.
I also updated the curation script to remove comments from things like intro.md, and updated the assign workflow to use the tidytuesdayR default "new_submission" folder if no folder is specified.
Closes #752.

Better intro.md instructions

---

.github/workflows/pr-assign-command.yaml

In theory this should automatically merge the main branch into the PR before trying to accept the submission.
Closes #740.

Merge main before accept.

---

file.feather

This file.feather showed up in root in the Amazon text submission.

Remove ghost file

---

data/2025/2025-02-18/readme.md
data/2025/2025-02-25/readme.md
data/2025/2025-03-04/readme.md
data/2025/2025-03-11/readme.md
data/2025/2025-03-18/readme.md
data/2025/2025-03-25/readme.md
data/2025/2025-04-01/readme.md
data/2025/2025-04-08/readme.md
data/2025/2025-04-15/readme.md
data/2025/2025-04-22/readme.md
static/templates/the_data.md

Hey, Jon! Ok, I've updated "PyDyTuesday" in the template file as well as all the previous weekly readmes so it says "pydytuesday". I've reinstalled and imported the pydytuesday package myself and had several people test it as well - all is good and pydytuesday installs and works from multiple different IDEs.

Libby Heeren patching - making pydytuesday lowercase in data template and previous weeks' folders 

---

data/2025/2025-10-07/readme.md

After reading the attached wikipedia article, Nelly, Nur, and I realized that the "Last season" data dictionary definition was inaccurate. We've corrected it to a more clear definition with a little more domain context. Upon reading up on the Euroleague, it seems like the standings are the places in which the teams finished in the Euroleague games, except for the final four, whose rankings reflect their standing after the final four match-ups. Rankings for the 2024-25 season can also be seen here: https://www.euroleaguebasketball.net/euroleague/standings/?season=2024-25&type=Traditional&phase=REGULAR%20SEASON

Update data dictionary entry for Last season var
