data/2019/2019-01-08/readme.md

This PR fixes the broken data link for the TV data.

fix relative path for data

---

data/2019/2019-02-26/readme.md

The CSV being read is `full_trains` so I think this is the intended object

Rename trains_raw <- to full_trains <-

---

data/2019/2019-11-05/bike_walk.R
data/2019/2019-11-05/readme.md

The "children" header row is row # 21, and data lines are rows 22-25.  For the other entities, the "slice" operation refers to the 1 minus the data line.  This children example is the outlier.

2019-11-05 - fix acs children_data slice

---

data/2019/2019-12-10/readme.md

adds the data dictionaries for the other datasets and fixes the copy and paste error where the second dataset was called diseases.csv as well.

fix typo and data dictionary

---

data/2019/2019-12-17/readme.md

Must have had a copy/paste from Word or something - fancy quotes crept into a demo line of code.

No fancy quotes in code

---

data/2020/2020-01-14/readme.md

leftover reference from last week, I assume

delete reference to weather stations

---

data/2020/2020-01-28/readme.md

Looks like dbh might be defined incorrectly in the data dictionary -- I poked around on the source website and couldn't find anything for the "depth, height" definition, but please correct me if I'm wrong in my interpretation!

Change dbh to diameter at breast height

---

data/2020/2020-03-10/readme.md

removed a typo so that `tuition_import` runs correctly

removed extraneous `_cost_` from tuition_income import

---

data/2020/2020-04-21/readme.md

gdpr_violations.tsv was listed as the data source for both dictionaries

data dictionary correction

---

data/2020/2020-04-28/readme.md

Noticed the dates/week was one behind

update tidytuesdayR dates/week

---

data/2020/2020-05-26/readme.md

"Cleaning Script" header was in the wrong place, `boston_cocktails.csv` header missing. Cheers.

fix wrong header data dict <> data cleaning

---

data/2020/2020-06-30/readme.md

updated year from 2020 to 2018

fixed typo

---

data/2020/2020-12-01/readme.md

Added a few links to grassroots/community led initiatives around homelessness in Toronto.
Thanks Tom!!!

Add ESN and tiny shelters to donations

---

data/2019/readme.md

Fix 2018 and 2019 data links

---

data/2021/2021-03-23/readme.md

unvotes has been on CRAN for 4 years 🙂; and a formatting tweak

Added cleaning script; small edits

---

data/2021/2021-01-12/readme.md

Just looking at this data for some inspiration and noticed Os' name is wrong here.

Fix Os' name

---

README.md

Fix typo in hyperlink for 2021-06-22 - public parks!

---

data/2021/2021-06-22/readme.md

missing the word "points" in the dogpark_points line

missing the word "points"

---

data/2021/2021-07-20/readme.md

Add a paragraph to explain why (eg) percentages don't seem to add to 100.

Clarify the semantics of "Cumulative" vs "Categorical" statistics

---

data/2021/2021-08-17/readme.md

just corrected the word 'characte' to character

typo of character

---

data/2021/2021-12-21/readme.md

the types of milk required to understand the data

milk types added

---

data/2022/2022-06-07/readme.md

The url to the `corp_by_politicians` csv file is incorrect in the readme.md file. It contains an additional 's'.
I propose the change of the object name and correction of the url.

URL to corp_by_politicians csv file is incorrect.

---

README.md
community_resources/README.md
community_resources/data/readme.md

Grammar Corrections

---

README.md

Ok this time we should really fix #496!

Fix 2023 link on main README.

---

data/2023/2023-01-24/readme.md

changed loudouts.csv to loadouts.csv

fixed a small typo in readme. 

---

data/2023/2023-05-09/readme.md

Table had an enter where there shouldn't have been an enter, messing up the table a bit. I fixed it

fixed typo in table

---

README.md
alt_text.md
data/2023/2023-07-25/readme.md
dataset_announcements.md
links.md
sharing.md

Make it a bit easier for people to find information about how to TidyTuesday.

Reorganize readmes

---

data/2023/2023-09-12/readme.md

changed global_economic_day.csv to global_economic_activity.csv

Fix filename for global_economic_day

---

data/2024/2024-03-05/readme.md

Updating readme and data files, removing the summary rows for professor, captain and gwynnda. 
https://github.com/rfordatascience/tidytuesday/issues/668

Update to remove summary rows in data

---

data/2024/2024-03-19/readme.md

Hi! Simple fix for the readme file of the tidy tuesday of the week that as broken

fix broken table in readme

---

data/2024/2024-03-26/readme.md

- replace `-` with `_` in variable names 
- add backticks for accessing data with tidytuesdayR

Deal with `-` in variable names in README for week 13

---

dataset_review.md

I intentionally don't link to this from anywhere yet. I intend to send people directly to this page via social media/Slack. If it's helpful, perhaps we'll promote it more. I can also imagine a relatively simple Shiny app that could streamline this process (applying labels directly, probably requiring a DSLC Slack login to access it to keep out spam + promote the community).

Instructions for reviewing datasets.

---

data/2024/2024-06-25/readme.md

To make sure it matches https://github.com/r-lgbtq/tidyrainbow

Capitalization tidyRainbow

---

.github/workflows/pr-assign-command.yaml
DESCRIPTION
static/templates/assign_week.R

I think I'll have to merge this to test it, but it should be pretty useful!

PR action to assign a dataset folder to a week.

---

data/curated/curation_scripts.R
data/curated/template/meta.yaml

Also tweaked some things in the meta.yaml template.

Update dictionary script for descriptions

---

static/templates/assign_week.R

In theory a setting in the repo will deal with the "merge master first" issue.

Properly use the credit name.

---

data/2025/2025-02-18/readme.md

Hi, Jon! Adding some context here since I'm submitting a readme change and not a data set. Here's an image with my changes circled. The part circled in green is the main change. The parts circled in yellow are minor suggestions only to make the language more inclusive! Please disregard those if you don't feel they're appropriate.
I also added a python chunk, so I modified your R chunk just a little to make it clear there's an R and a Python version below. If these changes are ok with you, I can make them to the template sections you shared with me and submit those PRs as well.
Thank you for all your help today!! Can't wait to get more people involved and build momentum for TT <3
Libby
---
Thank you for your submission! Please leave this text as-is when you submit, and then check the …

Update 2025-02-18 readme to include Posit Python challenge

---

data.txt
tidytuesday.Rproj

And add the new default RStudio ProjectId thing.

Delete unused files

---

README.md
data/2025/2025-02-18/readme.md
data/2025/2025-02-25/readme.md
data/2025/2025-03-04/readme.md
static/templates/how_to_participate.md

Hey, Jon! We wanted to update the language about Posit's Python initiative to be more in line with the ways we've seen the community engaging! That means using the #PydyTuesday hashtag, which is so fun! Thanks for being patient with us pivoting. I don't anticipate making many more changes anytime soon, but look forward to the chance to add python data download chunks as options in older week's repos in the future.
Libby
Thank you for your submission! Please leave this text as-is when you submit, and then check the checklist.
Usability:
Preparation:

Updating readme about PydyTuesday

---

README.md
data/2025/2025-04-29/readme.md
sharing.md

We have "ads" for Python and Julia where we used to have a language-agnostic section. This update re-agnosticizes the readme.
I also applied the Julia instructions for this week.

Agnostic README.
